version: '3.9'

services:

  database:
    image: mariadb:10.6.5
    container_name: hibernate-work-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hib
    ports:
      - "3306:3306"
    volumes:
      - hib_database:/var/lib/mysql:rw

volumes:
  hib_database:
